### ISSUE TITLE
Add row/new resource

### ISSUE THREAD

**Issue by Zireael07** [don-tnowe/godot-resources-as-sheets-plugin#10]
What it says on the tin :)

**Comment by don-tnowe** [comment]
With Resources, should be easy. But CSV direct editing is stored in a special way so gonna take a bit of extra effort.

**Comment by don-tnowe** [comment]
Should now be up! Duplicate, remove, rename, and clipboard actions on cells!

Not doing CSV today, though.

**Comment by don-tnowe** [comment]
Alright, CSV was easier than I made it to be. Will be up today.

**Comment by Zireael07** [comment]
Finally got some time to check, and I <3 it. Editing in this plugin allowed me to spot an instance where something was not in the column it should've been ;)

Bad news: the CSV import dialog seems to have gotten some focus problems (clicking on buttons does nothing, it wasn't present when I tried the plugin a week ago. I had to navigate to the buttons via keyboard, then it worked.)

**Comment by don-tnowe** [comment]
Just checked, not a problem for me HOWEVER, I got this while developing the feature 🤔

There seems to be an invisible Control covering up half of the buttons' area and capturing the input. Likely have filter set to `MOUSE_FILTER_PASS`, as they show the mouseover stylebox (mouse enter not handled) but can't get clicked (mouse press handled).

Opened #11 to gather info on this.
