### ISSUE TITLE
Beta 4.0 Changed OS.clipboard

### ISSUE THREAD

**Issue by scuzzar** [don-tnowe/godot-resources-as-sheets-plugin#12]
In Beta 10 of Godot 4.0 Changed OS.clipboard to DisplayServer.clipboard_get()

Needs to be fixed in res://addons/resources_spreadsheet_view/text_editing_utils.gd

**Comment by don-tnowe** [comment]
Funny, I changed it in one line but left the old method in the other two.

Will fix when I get to it, thanks for noting!
