### ISSUE TITLE
Warning spam about icon UID in Godot 4.0 asset store version 2.3

### ISSUE THREAD

**Issue by darloth** [don-tnowe/godot-resources-as-sheets-plugin#17]
When you do some stuff (I'm not quite sure what stuff exactly, but things involving typed cells, seems to be most display tasks) a warning is spammed to the debug console:

scene/resources/resource_format_text.cpp:448 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:3 - ext_resource, invalid UID: uid://c08qavfwqr3k7 - using text path instead: res://icon.png

This scene seems to have a saved UID that refers back to the default icon.png in the root of the project, but of course your UID isn't the same as my UID and so it complains a lot.  I can probably fix this for me by just matching our UIDs, but I don't think it should be referencing this file ( which is outside of the addon directory!) at all.  What if I didn't have this file for some reason, etc?

Suggested fix - add a default icon to the root addon directory, and reference that in the scene.  Something like res://addons/resources_spreadsheet_view/icon.png  That's if it needs to be set at all.

**Comment by don-tnowe** [comment]
Or just make that scene have no icon set 🤔 Does it disappear when there's no texture?

I'll look into this later, doesn't seem to be a critical issue.

**Comment by darloth** [comment]
Seems fine with no texture set, but I haven't actually tried to define a custom type or process anything with an image yet.

**Comment by don-tnowe** [comment]
Should be fixed in next patch.
