### ISSUE TITLE
Column widths are not updated properly. (3.5)

### ISSUE THREAD

**Issue by Frontrider** [don-tnowe/godot-resources-as-sheets-plugin#2]
I'm getting this error from the plugin:
```
scene/main/node.cpp:1362 - Index p_index = 5 is out of bounds (data.children.size() = 5).
res://addons/resources_speadsheet_view/editor_view.gd:220 - Invalid get index 'rect_min_size' (on base: 'null instance').
```

The log reminds me of a specific issue you can have with Godot. This happens when a child node you added was not ready yet when you tried to operate on it.(this means that `add_child` was still happening in the background.)

This can be averted by not working on the node, until it emits the "ready" signal.

![image](https://user-images.githubusercontent.com/6755034/192945393-1bb5691a-a51b-4a54-aa91-33bdc091d719.png)

I see that the error message is missing on the current godot-3 branch, but the issue still persists.

**Comment by don-tnowe** [comment]
Thanks for the report!

This cropped up for me too several times. Normally, it was fixed by hitting the Refresh button on the top bar - please try that for the time being. I'll look into it for a more consistent fix!

**Comment by don-tnowe** [comment]
Just fixed the error message AND something else while trying, now pushed. But it IS related!

Seems to be happening for me when I delete export properties in the class. Needs further investigation.

**Comment by Frontrider** [comment]
I see the yield in this line that wants to solve this, but honestly this is not a good solution in my experience. 
https://github.com/don-tnowe/godot-resources-as-sheets-plugin/blob/master/addons/resources_speadsheet_view/editor_view.gd#L217

Just let godot be async, connect to the `ready`/`tree_entered` signal with enough extra arguments to identify which column it is. That kind of code can be easier to read, while also being significantly more stable in my findings.

`node.connect("tree_entered",self,"update_target",[<needed arguments>],CONNECT_ONESHOT)`
- We connect to a signal that tells us that the node is indeed in the tree, so we can position it.
- the method is on the current object
- in the array we can pass down the node itself, some other markers like the column index
- we use `CONNECT_ONESHOT`, so the method will only fire once.

**Comment by Frontrider** [comment]
> Thanks for the report!
> 
> This cropped up for me too several times. Normally, it was fixed by hitting the Refresh button on the top bar - please try that for the time being. I'll look into it for a more consistent fix!

Also, pressing it repeatedly does nothing so this is not even a temporary solution.

**Comment by don-tnowe** [comment]
Should be much better now - removed the HBoxContainer right outta there. Might be wrong size, but fixable by refresh/resort and positions are correct.

Needs testing on whether that works consistently for someone other than me!

**Comment by Frontrider** [comment]
Seems to be fixed for me now.

**Comment by don-tnowe** [comment]
Helpful to know. Thank you! Leaving this open until I come up with a proper fix.

**Comment by Frontrider** [comment]
Would it be bad if I was thinking that it might be solvable by putting the headers into the grid view as well?

**Comment by don-tnowe** [comment]
Still a need for this? Fixed this on the 4.0 branch, can backport.

**Comment by Frontrider** [comment]
I have not been using this for a while now, and I most likely end up with a different solution. If nobody else needs this,then I'm not sure if it's worth backporting with godot 4 so close.

**Comment by don-tnowe** [comment]
Thank you for the heads-up! As it's not -really- blocking anything in the state I left it in, I'm closing this as resolved.
