### ISSUE TITLE
Preloaded script constants may conflict with global classes

### ISSUE THREAD

**Issue by pmorim** [don-tnowe/godot-resources-as-sheets-plugin#28]
Is this plugin compatible with Godot 4.1?
I'm just getting an empty UI and some console errors when opening the tab.

![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/77199990/3f4dfe4a-60af-4ccb-b0d1-38f29434065e)

**Comment by don-tnowe** [comment]
Should be, because I just used it on 4.1.0 yesterday :/

Will check on the latest-**latest** stable. Thank you a lot for providing the error messages!

**Comment by pmorim** [comment]
After some extra investigating, I found that the issue was that I already had a `SelectionManager` autoload conflicting with the one from this plugin.

Maybe prefix all of the `class_names` with the plugin name to reduce the possibility of conflicts? Or are there any other solutions?

**Comment by don-tnowe** [comment]
Uhhhhhh there are no `class_name`s. That is, most scripts that absolutely need to use that keyword are already prefixed - others are preloaded in constants WHICH IN TURN causes the conflicts, yeah.

Good catch! I can rename them, but would prefer to look for other options first 🤔
