### ISSUE TITLE
Add open resources in subfolders

### ISSUE THREAD

**Issue by Ohan17** [don-tnowe/godot-resources-as-sheets-plugin#30]
I have a list of characters which data is contained in modular folders, each with their own scene, script, texture, etc. It would be cleaner to be able to store resource files in the corresponding folders where they are used.
![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/66206021/26338aeb-d433-4e58-86a3-b17b5c2e5e38)

**Comment by don-tnowe** [comment]
Good idea, I planned recursive scanning but forgot! If there's only one custom resource per folder, should be easy - but if there are different types of **custom** resources, say, a `CharacterStats` and `CharacterBehaviour` in each, the table can't be built - I still need #24 sorted out.

**Comment by don-tnowe** [comment]
The feature's up (9b826b5539a0abde8f10e89e68d7c221d22d6807) so should be usable for your case! But for multiple custom types, I'd like to move the discussion into #24.
