### ISSUE TITLE
Saving custom defined enum value incorrectly

### ISSUE THREAD

**Issue by Ohan17** [don-tnowe/godot-resources-as-sheets-plugin#31]
The plugin will save default enum value (its order in enum) instead of the defined value with export enum or array enum.
Godot v4.1.1
![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/66206021/f589e19f-7aa3-4f0c-ad1c-287bd347cdb6)
![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/66206021/e92787fc-a655-4b7b-9f54-e12c38c5ef07)
![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/66206021/67ba863f-93c8-480f-98e5-957ed843d93c)
[MRP.zip](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/files/12454075/MRP.zip)

**Comment by don-tnowe** [comment]
Whew, glad I just fixed non-named values causing exceptions.

Thanks for the MRP! I'll look into it.
