### ISSUE TITLE
Importing an exported CSV doesn't update existing resource files

### ISSUE THREAD

**Issue by kipplesunderscore** [don-tnowe/godot-resources-as-sheets-plugin#34]
This may not be a current feature - but we made some simple resource files, and then exported them as a CSV.

This works great! Pretty much exactly as you'd hope, all the data in the CSV, editable, very cool and potentially powerful.

The only issue we've had is importing this file back in, with changes. We figured that doing so would then update our original resource files from which we exported - but instead it seems to create a new resource file named after the excel sheet (if using 'confirm and edit') or it creates brand new resource files with a new custom script (if using convert to resources and edit)

We're pretty sure we might just not know the intended use case for this feature, but are hoping maybe we're making a mistake somehow and this might work!

**Comment by don-tnowe** [comment]
Wait, you're converting `.tres` files into a `.csv`, then modifying from outside, then back to `.tres`? That's what "Confirm and edit" is for! You can just edit the CSV directly.

If you really need them as `.tres` files in the end result, then ~just edit the resources with the addon~ you might need to delete the old resources from outside Godot, then convert the CSV data into resources, then replace the new script of all the resources to your own script using the plugin.

I will add proper native support for this workflow later.

**Comment by don-tnowe** [comment]
Trying to implement this at least halfway, putting on hold now. Found issues:

- converting CSV to resources, destination path can't be set. Window must allow setting the destination folder - the script for the new resources will be grabbed from those already inside, if any;
- need warning about datatypes. Enums might not be re-imported 1:1, some datatypes can't be reimported at all, and resource paths inside arrays/dicts become invalid
- enums cut last character #35 . Unrelated, but good to know as it's destructive.
