### ISSUE TITLE
Objects without script do not show in editor

### ISSUE THREAD

**Issue by Red-Ward-Studio** [don-tnowe/godot-resources-as-sheets-plugin#37]
Functionality is unclear - docs suggest any Resource will be shown as spreadsheet but *.tres files representing Materials don't seem to show, example folder works fine.

![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/118481462/7c7732fe-48eb-4451-9932-9585b442a799)

**Comment by don-tnowe** [comment]
Oof, yeah that was a lie on my part. Currently, it scans resources with the same script, which requires them to have a script. So as workaround, attaching script with only an `extends Resource` might be fine.

Good use for the plugin, material configs are heckin' chonkers. I'll fix this up.

**Comment by don-tnowe** [comment]
It's up on this repo (*Godot-4 branch*). Picks most common base type or class.

One unrelated thing to note for this type is that properties are grabbed from the first resource sorted by filename, if you want to edit things like emission or rimlight.
