### ISSUE TITLE
Array of enums

### ISSUE THREAD

**Issue by Frontrider** [don-tnowe/godot-resources-as-sheets-plugin#4]
This is probably not solvable, but a solution for an array of enums would be nice, right now it shows an array of ints.

**Comment by don-tnowe** [comment]
Huh. Didn't even know this was possible knowing Enums can't be set as types anywhere else in GDScript. I'll put this on the planned feature list, though. Thank you!

**Comment by Frontrider** [comment]
I do not know if it's possible, I just threw this in.

**Comment by don-tnowe** [comment]
Export hint strings for enum arrays contain all enum values, sooooooo... 😉

**Comment by don-tnowe** [comment]
Ping!
