### ISSUE TITLE
Is Godot 4.2 supported ? 

### ISSUE THREAD

**Issue by francoisdlt** [don-tnowe/godot-resources-as-sheets-plugin#42]
I just installed the plugin on my Godot 4.2 project, and I'm having trouble using the plugin. 
In particular, editing enum or String values is very weird (no caret, no sub window popping for massediting, etc)
Also the process function does not seem to work
But maybe i'm just missing the user manual ?

**Comment by francoisdlt** [comment]
one of the use-cases that I'm looking to achieve is highlighting resources that contain un-localized labels (Strings that have no translation in the localization CSV. i usually use the following test : `value != tr(value)`)

**Comment by don-tnowe** [comment]
Enums don't have dedicated edit functionality - unless it's an array of these, they're either edited as numbers on the bottom or through the Inspector on the right, basically the cells themselves only edit text - but I'll note this in #43. For strings, carets don't appear unless they're inside the text (*that is, Left arrow or Home are pressed*). But if they are and the caret's invisible, it is indeed a bug.

Process is for modifying the resources - for filtering, input your expression into the Condition field!

In case it's a bug, then if you are getting an errors in the Output log, I'd like to see a screenshot so I can know where the troubled code is. In addition, could you please send me some of your resources so I can reproduce the bug, in case it's a problem with reading data, as well as the expression you're inputting?

**Comment by francoisdlt** [comment]
OK I understand better. It seems the TranslationServer is not initialized for editor plugins so I cannot really achieve what I'm looking for anyway. 
and for my enums I just realized that I have custom _get_property_list() on my resources which might not play nicely with your plugin.

**Comment by don-tnowe** [comment]
Actually, `_get_property_list()` should work unless the first Resource in the folder (*alphabetically*) doesn't have the property (*source: tested with WorldEnvironment and custom lists*), so again, in case it doesn't then it's a bug I'd like to fix!
