### ISSUE TITLE
Exporting a CSV with a multiline text attribute returns an error ("line.size() <= 1" is true)

### ISSUE THREAD

**Issue by avivajpeyi** [don-tnowe/godot-resources-as-sheets-plugin#44]
I'd be great if this can be permitted. I'd be happy to help try to add this feature in? 

![Screenshot from 2023-12-11 14-16-45](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/15642823/a0a10e3e-99d4-43c9-838e-afed3c3342cc)
![Screenshot from 2023-12-11 14-16-39](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/15642823/6a70392d-d81b-46f1-90a1-821bf86cbeb5)

**Comment by don-tnowe** [comment]
Does it still export? By default, Godot reads CSV as translations, and because the first row isn't translation codes it gets super mad. Setting the file's import settings should remove it
