### ISSUE TITLE
Cell editing doesn't seem to work right in 4.2

### ISSUE THREAD

**Issue by derkork** [don-tnowe/godot-resources-as-sheets-plugin#47]
So I just downloaded the plugin into 4.2 and tried to edit the example data that came with it. Whenever I try to type into a selected cell, after I type one character, this character is added into the cell and then the cell is deselected automatically.  Here I try to replace the value with 5:

https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/327257/c5fc0f75-aa1d-4b2c-8b5f-4a2f4ba673e9

This makes it almost impossible to do any edits. I also tried copy/pasting cell values, but pasting appends to the cell value rather than replacing it. Here I copy the value 2 and try to paste it into several other cells and it gets appended.

https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/327257/937a8e21-f38c-40b4-b7aa-d4da654e5622

Same thing happens when I try to edit multiple cells. E.g. here I try to change all these values to "7":

https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/327257/1f610ec0-4630-4c2b-bdca-d22ac5f19cc0

But instead the number is just appended. And again everything is deselected after I type the 7.

Am I using this the wrong way?

**Comment by don-tnowe** [comment]
Doesn't happen on my end ( 61603e5a23848abf888db0136c33c0e7b1b8ccc0 ), but your console doesn't seem to print anything to indicate a problem. Something's causing the table to update, but I'll need to know more to fix this.

Regarding numbers appending instead of replacing: it's intentional, numbers can be erased via `Ctrl+Backspace+Backspace`.

**Comment by don-tnowe** [comment]
Wait, I tried with the item example and it breaks like that too. That'll narrow it down.
