### ISSUE TITLE
"Fill with sequence" has no visible effect

### ISSUE THREAD

**Issue by derkork** [don-tnowe/godot-resources-as-sheets-plugin#48]
I'm trying to fill a set of rows with the same value. I'm using Godot 4.2 and the example data that came with it. From the help popup I gather that you only need to set the start value and then all selected cells should be filled with the start value:

![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/327257/410d54e1-0186-48ec-8d63-bb51b39b4b8e)

However, if I try to set the value of these selected cells to 5, then nothing visible seems to happen when I click the Set button, except that it prints "Set Cell Values" in the log.

https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/327257/f655e7e6-6476-4efd-8668-ce147895fa67

**Comment by derkork** [comment]
Seems to be caused by an invisible label in the scene. This was probably added later but breaks the code that reads the sequence fields:

![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/327257/c6b7a298-3ee6-45d2-bdbb-26fd5ad26fb3)

**Comment by don-tnowe** [comment]
Ah, I remember why I added this. I'll fix that.
