### ISSUE TITLE
Nicer column names

### ISSUE THREAD

**Issue by Frontrider** [don-tnowe/godot-resources-as-sheets-plugin#5]
I'm carpet-bombing a bit, but at least this one is easy.

You can use this to make the table headers more human readable.
https://docs.godotengine.org/en/3.5/classes/class_string.html#class-string-method-capitalize

**Comment by don-tnowe** [comment]
No worries. This gives me a feeling that at least someone needs me.

It's not just `String.capitalize`, but I do have code to do that lying around.
