### ISSUE TITLE
"bool" type fields are not editable

### ISSUE THREAD

**Issue by robotjunkyard** [don-tnowe/godot-resources-as-sheets-plugin#50]
Unless I'm missing something under my nose, it seems that fields of a Resource which are of type "bool" are not editable, unlike other fields which are of other types.

**Comment by don-tnowe** [comment]
It's editable, just with a keyboard. Key press toggles it if it's selected - just not a click as one would expect.

There's a bunch of these, actually - enums, arrays, dictionaries and resources aren't editable either!

Related: #43
