### ISSUE TITLE
[Help Wanted] Use as a CSV Editor?

### ISSUE THREAD

**Issue by chaojian-zhang** [don-tnowe/godot-resources-as-sheets-plugin#51]
Hi, thanks for the great plugin! Works as expected.

I have a small feature request that I think this plugin will be great for - can you shed some light on how this plugin might be used to modify usual CSV files, i.e. not for resource purposes? I think the plugin has all the components but I just need some guidance on how to repurpose it to just for editing CSV.

Essentially I am looking for something like this for Visual Studio Code: https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv

E.g.

|Employee ID|Employee Year|Employee Department|
|-|-|-|
|001|2|Accounting|
|003|2|Finance|

Thanks!

**Comment by don-tnowe** [comment]
Hello! Interesting use case.

It's definitely already possible: `Import/Export CSV` -> Specify columns and datatypes (*there are enums too*) -> `Confirm and edit`.
