### ISSUE TITLE
Allow editing all Resources of a same type in the whole project 

### ISSUE THREAD

**Issue by Hyrilorius** [don-tnowe/godot-resources-as-sheets-plugin#53]
Being able to edit all resources within a folder is cool.

But in addition, it would be great if we were able to edit all existing Resources in the project of a specific type wherever they are in the project.

This way we would be able to organize our projects as we want, sometimes it doesn't make sense to put resources from the same type in the same folder. It happens often we want to put resources related to a scene in a folder specific to a scene.

Being able to create sheets per folder or per resources types would be the best of both world.

The two methods of filtering could also be mixed if it's not to hard too implement. 
This way we would be able to find all Resources of a said type within a specific folders and all its nested subfolders.

**Comment by don-tnowe** [comment]
Already possible... if you only have one type of Resource.

Related: #38. If that gets implemented, then technically this should be possible!

**Comment by Hyrilorius** [comment]
Ahah, usually we have a lot of different type of resources in a game that are very different from each other (CharacterStats VS ItemData for example)

My point is that I could have ItemData at many different places in my FileSystem, but would like to still be able to edit all of them in a table. But I don't want all CharacterStats to be display in the same table, as they don't share anything in common (same for all other resources types in my game)

**Comment by don-tnowe** [comment]
Yeah! Which is why I'd have to first think how to best implement it UI-wise.

**Comment by GideonWolfe** [comment]
Any update on this?

I (and many others) prefer to have the resource grouped together with its corresponding item rather than dumped in a single directory

**Comment by don-tnowe** [comment]
This is already possible by filtering for a specific script: `res.get_script().resource_path.ends_with("your_script.gd")`. However, this does not consider class inheritance. If there is a reliable and easy way to check inheritance in editor, please let me know!

**Comment by don-tnowe** [comment]
I implemented this in the `Godot-4` branch. For bugs, please open another issue!
