### ISSUE TITLE
Have the functions of the "||" button as a "right click menu"

### ISSUE THREAD

**Issue by Frontrider** [don-tnowe/godot-resources-as-sheets-plugin#6]
Just added hiding any columns via the "||" and "Show/Hide Columns (Eye icon)" buttons, so closing this as solved!

_Originally posted by @don-tnowe in https://github.com/don-tnowe/godot-resources-as-sheets-plugin/issues/3#issuecomment-1264335906_
      

This is coming from this, as I was right clicking those columns a few times and I sometimes still do thinking that it would give me more options.

Looking at the code, I'd also pack the popup into the `res://addons/resources_speadsheet_view/table_header.tscn` scene as well, just to keep it contained, and readable. It can output values via signals.

**Comment by don-tnowe** [comment]
Yeah, does feel like it. I kept it as a separate button for discoverability, but making "just right-clicking" an option sounds only beneficial!

**Comment by Frontrider** [comment]
It also suffers from the same bug as the other one does, you can switch main screens and it remains open.

**Comment by Frontrider** [comment]
This seems to be a working fix, the header script can emit the events related to the popup inside the menu button, the popup will open on right clicks, and we can also fetch the left click event with a gui input hook on the menu button. The visuals do work in a strange manner, but at least it works without any annoying bugs.

![image](https://user-images.githubusercontent.com/6755034/193466343-8cfa7c6f-9040-4a4c-bc00-ef5f3ae5758c.png)

**Comment by Frontrider** [comment]
Now I'm clicking the button thinking it will sort it xD
