### ISSUE TITLE
Columns for hidden/filtered resources still show up

### ISSUE THREAD

**Issue by rsubtil** [don-tnowe/godot-resources-as-sheets-plugin#60]
We have a project where we store all resource data to a folder. However, we also have another subfolder with more specialized behavior that is implemented as a resource as well, in a `custom behaviors` folder:
```
status effects
├── burn.tres
├── common scripts
│   ├── EffectBehavior.cs
│   └── Effect.cs
├── custom behaviors
│   ├── BurnEffectBehavior.cs
│   ├── burn_effect_behavior.tres
│   ├── poison_effect_behavior.tres
│   └── PoisonEffectBehaviour.cs
├── parry.tres
└── poison.tres
```

![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/6501975/dd2c3d54-9a78-4d76-b0b2-073cf4488ac3)

The `filter/process` allows us to hide such resources from the view. However, the columns from such resources still show up, even though they're undefined for any of the other visible types:
![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/6501975/a6fe0068-6845-41b3-9263-93b9a54d34d1)

**Comment by don-tnowe** [comment]
Interestingly, editing of several resource types and these "empty cells" are a recent feature, glad to see more people needed it. I do plan on fixing this too!
