### ISSUE TITLE
Allow editing nested arrays of resources

### ISSUE THREAD

**Issue by Tam** [don-tnowe/godot-resources-as-sheets-plugin#62]
I have some resources that contain an array of other resources. Is it possible to expand the array and edit the resources inside?

<img width="641" alt="Screenshot 2024-05-12 at 23 12 51" src="https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/977594/330f7cfd-4c78-44f0-8310-d4acfdfb78cf">

**Comment by don-tnowe** [comment]
It is currently not a feature.

Mass modification of nested resources is only possible by writing an expession or function inside the `Filter/Process` -> `Process` field.

It could be possible to view all subresources in a folder of `tres` files, if there was a way to insert empty rows to separate arrays and insert a resource picker to add resources to arrays. I will note this as a future addition!

**Comment by don-tnowe** [comment]
I have pushed an implementation. If still relevant, I invite to test! @Tam @eobet

- This is a context menu in the column header - right-click the button or left-click the arrow. This is also in the context menu after clicking a cell, if valid.
- Opens subresources in the whole column, or only selection.
- Each resource is only shown once, if linked to from multiple places.

I would like opinions on whether the option's name and its UI is descriptive for the feature.
