### ISSUE TITLE
Editing a cell inline edits the resource name instead of the resource field value

### ISSUE THREAD

**Issue by adadgio** [don-tnowe/godot-resources-as-sheets-plugin#65]
<img width="538" alt="Screenshot 2024-09-18 at 16 24 22" src="https://github.com/user-attachments/assets/6a2b1487-1bfb-4767-b968-ec0621ad40ae">

Hi, this is probably not intended, but editing a call actually changes the full resource name ".tres" file.

**Comment by don-tnowe** [comment]
Bizarre. Which cell/property were you changing and how, and in what way did it change the filename?

The resource path column is hard-coded to never be editable via keyboard or text pasting. It is possible to copy them, and, with a special separate action, rename the resources.

Were you clicking the "✏" button? That is, as the tooltip says, intended for renaming the resource and not editing the cell.

**Comment by don-tnowe** [comment]
No, it is actually possible. You simply need to select a cell and type away at your keyboard, like you're already in a text field. This supports most cursor movement operations from text editors, too.
