### ISSUE TITLE
Improve experience of adding Resources through bottom dock

### ISSUE THREAD

**Issue by don-tnowe** [don-tnowe/godot-resources-as-sheets-plugin#66]
Here are some features that could improve the bottom dock for Resource arrays:

- add resource right as it is inserted into the picker. This helps add resources without an extra button click, hopefully not interfering with creation of new, local resources.
- allow dragging multiple resources into the dock.
- save recently added resources, like the other array docks do.

**Comment by PangolinMontanari** [comment]
Dragging multiple resources into place (such as if the cell represents an array) would be huge for me also. In the broader sense this is something inexplicably missing from Godot at large, but regardless of that having the option to do that for arrays would be far better than what exists here.
![image](https://github.com/user-attachments/assets/26f76c2c-7c6e-4a9f-96ae-fcfcdc56b532)
I only just now figured out the functionality of the central panel is, and I'm still not sure what the left and right panels do at all.

**Comment by don-tnowe** [comment]
Yeah, the left and right panels don't do much here. But they do work for arrays of strings. I will work on this, seeing it's needed.

> inexplicably missing from Godot at large

Wait, I thought they brought this back? I guess it's still stuck back in the Godot 3.x inspector.

**Comment by don-tnowe** [comment]
This feature has been implemented. For bugs, please open a new issue!
