### ISSUE TITLE
Godot 4.3 support

### ISSUE THREAD

**Issue by nadvornikjiri** [don-tnowe/godot-resources-as-sheets-plugin#68]
Hi, on the Godot version 4.3, I'm getting the following errors when trying to load the plugin:
`
  res://addons/resources_speadsheet_view/import_export/formats_edit/edit_base.gd:2 - Parse Error: Could not find base class "Reference".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/formats_edit/edit_base.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/import_export/formats_edit/edit_csv.gd:2 - Parse Error: Could not resolve super class inheritance from "SpreadsheetEditFormatTres".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/formats_edit/edit_csv.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/import_export/formats_edit/edit_tres.gd:2 - Parse Error: Could not resolve super class inheritance from "SpreadsheetEditFormat".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/formats_edit/edit_tres.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/import_export/formats_export/export_csv.gd:2 - Parse Error: Could not find base class "Reference".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/formats_export/export_csv.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/import_export/formats_import/import_csv.gd:2 - Parse Error: Could not find base class "Reference".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/formats_import/import_csv.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/import_export/import_export_dialog.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/import_export_dialog.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/import_export/import_export_enum_format.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/import_export_enum_format.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/import_export/property_list_item.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/property_list_item.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/import_export/spreadsheet_import.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/import_export/spreadsheet_import.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_cells/cell_editor.gd:19 - Parse Error: Used space character for indentation instead of tab as used before in the file.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_cells/cell_editor.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_cells/cell_editor_array.gd:2 - Parse Error: Could not resolve super class inheritance from "CellEditor".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_cells/cell_editor_array.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_cells/cell_editor_bool.gd:1 - Parse Error: Could not resolve super class inheritance from "CellEditor".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_cells/cell_editor_bool.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_cells/cell_editor_color.gd:1 - Parse Error: Could not resolve super class inheritance from "CellEditor".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_cells/cell_editor_color.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_cells/cell_editor_enum.gd:1 - Parse Error: Could not resolve super class inheritance from "CellEditor".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_cells/cell_editor_enum.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_cells/cell_editor_enum_array.gd:15 - Parse Error: Expected statement, found "." instead.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_cells/cell_editor_enum_array.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_cells/cell_editor_resource.gd:1 - Parse Error: Could not resolve super class inheritance from "CellEditor".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_cells/cell_editor_resource.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_cells/cell_editor_string.gd:1 - Parse Error: Could not resolve super class inheritance from "CellEditor".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_cells/cell_editor_string.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_editors/dock_array.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_editors/dock_array.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_editors/dock_base.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_editors/dock_base.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_editors/dock_color.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_editors/dock_color.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_editors/dock_enum_array.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_editors/dock_enum_array.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_editors/dock_number.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_editors/dock_number.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/typed_editors/dock_texture.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/typed_editors/dock_texture.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/editor_icon_button.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/editor_icon_button.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/editor_stylebox_overrider.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/editor_stylebox_overrider.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/editor_view.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/editor_view.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/plugin.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/plugin.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/selection_actions.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/selection_actions.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/settings_grid.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/settings_grid.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/table_header.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/table_header.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/table_pages.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/table_pages.gd" with error "Parse error". (User)
  res://addons/resources_speadsheet_view/text_editing_utils.gd:2 - Parse Error: Could not find base class "Reference".
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/text_editing_utils.gd" with error "Parse error". (User)
  (2) drivers/windows/file_access_windows.cpp:181 - Case mismatch opening requested file 'res://main.cs', stored as 'res://./Main.cs' in the filesystem. This file will not open when exported to other case-sensitive platforms.
  res://addons/resources_speadsheet_view/plugin.gd:0 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_speadsheet_view/plugin.gd" with error "Parse error". (User)`

**Comment by don-tnowe** [comment]
Yep, this seems to be errors from the `3.x` version, which is currently in the `main` branch. Try downloading from the AssetLib from inside the game engine, or from https://github.com/don-tnowe/godot-resources-as-sheets-plugin/tree/Godot-4.

This Github repo is set up so confusingly because I was updating the Godot 3.x version for some time, which means the Git branches have diverged and I'd need to sift through Git conflicts to merge the branches.

**Comment by nadvornikjiri** [comment]
This is the head of Godot-4 branch ;).

**Comment by nadvornikjiri** [comment]
Sorry, pasted wrong output when I was playing with the branches. *This* is the output for Godot-4 branch:
` res://addons/resources_spreadsheet_view/main_screen/class_filter.gd:89 - Parse Error: The variable type is being inferred from a Variant value, so it will be typed as Variant. (Warning treated as error.)
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_spreadsheet_view/main_screen/class_filter.gd" with error "Parse error". (User)
  res://addons/resources_spreadsheet_view/main_screen/column_header_manager.gd:8 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/main_screen/column_header_manager.gd:9 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/main_screen/column_header_manager.gd:10 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_spreadsheet_view/main_screen/column_header_manager.gd" with error "Parse error". (User)
  res://addons/resources_spreadsheet_view/editor_view.gd:8 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/editor_view.gd:9 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/editor_view.gd:10 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/editor_view.gd:11 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/editor_view.gd:12 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/editor_view.gd:13 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/main_screen/selection_manager.gd:12 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/main_screen/selection_manager.gd:13 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/main_screen/input_handler.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_spreadsheet_view/main_screen/input_handler.gd" with error "Compilation failed". (User)
  res://addons/resources_spreadsheet_view/main_screen/recent_paths.gd:4 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_spreadsheet_view/main_screen/recent_paths.gd" with error "Parse error". (User)
  res://addons/resources_spreadsheet_view/main_screen/selection_actions.gd:13 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  res://addons/resources_spreadsheet_view/main_screen/selection_actions.gd:14 - Parse Error: "@onready" will set the default value after "@export" takes effect and will override it. (Warning treated as error.)
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_spreadsheet_view/main_screen/selection_actions.gd" with error "Parse error". (User)
  res://addons/resources_spreadsheet_view/typed_editors/dock_array.gd:240 - Parse Error: The variable type is being inferred from a Variant value, so it will be typed as Variant. (Warning treated as error.)
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_spreadsheet_view/typed_editors/dock_array.gd" with error "Parse error". (User)
  res://addons/resources_spreadsheet_view/typed_editors/dock_dict.gd:158 - Parse Error: The variable type is being inferred from a Variant value, so it will be typed as Variant. (Warning treated as error.)
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_spreadsheet_view/typed_editors/dock_dict.gd" with error "Parse error". (User)
  res://addons/resources_spreadsheet_view/typed_editors/dock_enum_array.gd:121 - Parse Error: The variable type is being inferred from a Variant value, so it will be typed as Variant. (Warning treated as error.)
  modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/resources_spreadsheet_view/typed_editors/dock_enum_array.gd" with error "Parse error". (User)`

**Comment by nadvornikjiri** [comment]
My Godot version: 
![image](https://github.com/user-attachments/assets/ff0ff66c-6698-4b24-865b-d41b7553588d)

**Comment by don-tnowe** [comment]
Seeing a lot of `(Warning treated as error)`, so this is about your Project Settings config.

The `debug/gdscript/warnings/exclude_addons` project setting should ignore warnings in addons, but it seems to ignore warnings set to be treated as errors 🤔 If you have it enabled and see this, worth opening an issue on the Godot Suggestions repository, since it definitely shouldn't be the way it works.

**Comment by nadvornikjiri** [comment]
Oh don't worry, I don't treat warnings as errors myself, I'd be fine with them if it worked, but I can't open the ResourceTables view, it throws this error:
`res://addons/resources_spreadsheet_view/plugin.gd:34 - Invalid access to property or key 'current_path' on a base object of type 'MarginContainer (editor_view.gd)'.`

It worked with older Godot versions, but I'd need to dig into which, didn't use it for a while. But it was 4.x version for sure.

**Comment by nadvornikjiri** [comment]
This might be leading to that:
`res://addons/resources_spreadsheet_view/plugin.gd:10 - Invalid assignment of property or key 'editor_interface' with value of type 'EditorInterface' on a base object of type 'MarginContainer (editor_view.gd)'.`

**Comment by don-tnowe** [comment]
This error is saying that `editor_interface` and `current_path` are not properties inside `editor_view.gd`, but checking the script, it exists. This happens when the script failed to compile due to another error, so the real problem will be higher up in the engine log!

> Oh don't worry, I don't treat warnings as errors myself, I'd be fine with them if it worked!

Well, the editor clearly isn't! 😄 I'm checking editor settings now, and I'm seeing the two warnings you mention are set to `Error` by default now, which doesn't seem to cause a problem on my end. I'll update those now, thanks!

**Comment by nadvornikjiri** [comment]
Ok, so there would be a fix coming? Or do I need to fix something in my config?

**Comment by don-tnowe** [comment]
I've updated it, now this should be fixed. Forgot to push to AssetLib, in some time the fix will be there too.

**Comment by nadvornikjiri** [comment]
Splendid, I can confirm it works in the Godot-4 branch now. Thanks :).
