### ISSUE TITLE
Missing CSV export option

### ISSUE THREAD

**Issue by the-old-one** [don-tnowe/godot-resources-as-sheets-plugin#69]
When editing a resource folder and clicking the "Import/ExportCSV..." button there's only the Open button and no option to export.

Godot 4.3 .NET, Windows 11. `master` branch.

Not sure if it's a bug but I couldn't find a manual describing the CSV export feature.

<img width="478" alt="image" src="https://github.com/user-attachments/assets/878e45b5-6a12-4bfb-9fa5-1f4fc005524f">

**Comment by don-tnowe** [comment]
Yep, the export is done into an existing `.csv` file. There should be a button to create one, but it seems to have disappeared when the engine updated. I saw a new way of adding buttons so I will use that.

**Comment by don-tnowe** [comment]
Should be fixed with f7b800851f7f487c51c77d36685e8c59a4eb935d . Now the dialog is both an "Open File" and an "Open Folder" dialog, so filename can be entered to create a file.
