### ISSUE TITLE
The "toggle visibility" popup can only be closed by clicking the button again.

### ISSUE THREAD

**Issue by Frontrider** [don-tnowe/godot-resources-as-sheets-plugin#7]
![image](https://user-images.githubusercontent.com/6755034/193456157-6dd0b29b-c894-4591-9484-d5767c279327.png)
![image](https://user-images.githubusercontent.com/6755034/193456196-9e8e76fa-9a8b-4d95-858c-beb3ec051f13.png)

The title says it, I can click anywhere and it will stay open. I can even open other popups as well. At the same time.

I'd try to solve it by using a menu button, as that provides the needed functionality, and yes I would make that button group flat as well.

**Comment by Frontrider** [comment]
You told me it makes you feel important that I nitpick it, now I will. :P

**Comment by Frontrider** [comment]
I could make a PR for it, but I don't feel comfortable touching this codebase. 

This could be a small "redesign". Flat buttons, as they don't need highlights imo, and a separator between it and the other menus. ![image](https://user-images.githubusercontent.com/6755034/193456439-5f6b150f-e419-460e-b9d8-ba85e4792785.png)

Using a menu button would be especially important, as the button can be clicked in a way that makes it difficult to close.
![image](https://user-images.githubusercontent.com/6755034/193456622-7d93149c-6037-4017-81b6-0d234ea27d4d.png)

**Comment by don-tnowe** [comment]
Thank you for the report

Yes it can, and it is indeed a problem. It should be able to be closed by just clicking due to configuration, but it doesn't seem to even after the editor Main panel is switched (*so not the plugin eating the click up*). Also the case with the column header menu.

I'll look into a workaround.

**Comment by Frontrider** [comment]
> I'll look into a workaround.

Use a menu button for this, that is what you wanted to do in that spot. That contains all the logic you need already.

**Comment by don-tnowe** [comment]
It might, but I remember having some reasons not to do that. When I have time though, I'll try it.

**Comment by Frontrider** [comment]
> It might, but I remember having some reasons not to do that. When I have time though, I'll try it.

I actually tried that now out of curiosity, and I saw no issues, when this uberscript was behaving >.<. The only issue I think you could have had is setting the popup's contents which is still not hard.

**Comment by Frontrider** [comment]
https://github.com/don-tnowe/godot-resources-as-sheets-plugin/blob/07f52150f7db746595bbbea612a9683c11298c57/addons/resources_speadsheet_view/editor_view.gd#L205-L211

It's full of stuff where it just breaks simple encapsulation. (I hope that's not insulting, not my intention)

**Comment by don-tnowe** [comment]
Aaaaaah, I remember why I didn't make them MenuButtons. They insisted on being `flat` no matter what I set in properties 🤨 And they can't be flat because, like, they don't feel like buttons there, but rather, some status indicators. (*stupid, yes, but I saw no downsides... at the time*)

I'm also gonna refactor this junkyard of a megaclass, yes. At the beginning there was a (*solution then unknown*) issue with adding classes (*figured later: project restart instead of just re-enabling plugin*), so I guess that just stuck ¯\_(ツ)_/¯

**Comment by Frontrider** [comment]
> Aaaaaah, I remember why I didn't make them MenuButtons. They insisted on being flat no matter what I set in properties raised_eyebrow And they can't be flat because, like, they don't feel like buttons there, but rather, some status indicators. (stupid, yes, but I saw no downsides... at the time)

I'm gonna propose a viable solution: Build a menu bar out of these.

**Comment by Frontrider** [comment]
![image](https://user-images.githubusercontent.com/6755034/193470187-219c57f7-da1d-4b26-95dd-2abca6f723db.png)
Not sure how long I can go with this, but pushing what I did today onto a fork.

**Comment by don-tnowe** [comment]
Wait, I just pushed this here 😂

**Comment by don-tnowe** [comment]
There's still a bug with the header right-click, but hopefully it's not **too** bad. Closing as resolved.

**Comment by Frontrider** [comment]
> Wait, I just pushed **almost** the same thing here joy

Almost, except mine started to be extracted and saving things no longer works.
