### ISSUE TITLE
Addon can't be downloaded from the asset store. Error 404

### ISSUE THREAD

**Issue by the-old-one** [don-tnowe/godot-resources-as-sheets-plugin#70]
When trying to download the plugin from the asset store getting the error Failed: 404
Godot 4.3 .NET

<img width="464" alt="image" src="https://github.com/user-attachments/assets/86d221d7-a801-45b0-ac62-0c0c698058c9">

**Comment by kblaedel** [comment]
Aha that makes total ssense. Thanks!
