### ISSUE TITLE
404 from godot asset page, and then 404 on github

### ISSUE THREAD

**Issue by DanielBurdock** [don-tnowe/godot-resources-as-sheets-plugin#71]
I tried to download the resource as tables plugin, however I got a 404 from inside godot so I tried to download it from the assets page and got this error:
404 - page not found
The Godot-4 branch of godot-resources-as-sheets-plugin does not contain the path archive/5dabeb72678d19118192ea83938a3642450bfa54.zip.

**Comment by don-tnowe** [comment]
This is an issue with the AssetLib listing. A fix has been submitted, so it will be resolved once the update is approved.

For now, please download or clone this repository's main branch.

**Comment by DanielBurdock** [comment]
> This is an issue with the AssetLib listing. A fix has been submitted, so it will be resolved once the update is approved.
> 
> For now, please download or clone this repository's main branch.

Thank you for the reply, much appreciated :)
