### ISSUE TITLE
Searching breaks the entire display.

### ISSUE THREAD

**Issue by Frontrider** [don-tnowe/godot-resources-as-sheets-plugin#8]
I typed in `res.tags.has("elemental")`, and this is the result.

![image](https://user-images.githubusercontent.com/6755034/193470858-5e743531-df60-401a-a582-6d32484e1580.png)

**Comment by don-tnowe** [comment]
Definitely an issue with hidden columns. Looks like conditions for hidden **columns** and hidden (*by search*) **rows** are conflicting.
